create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  sub_category text not null,
  price numeric not null,
  stock int default 0,
  image text,
  description text,
  created_at timestamp with time zone default now()
);

create table orders (
  id bigint generated by default as identity primary key,
  customer jsonb not null,
  items jsonb not null,
  total numeric not null,
  status text default 'received',
  created_at timestamp with time zone default now()
);
